POST {{check_host}}/checkCode/getCheckCode
# key
# user:register:code:手机号   auth:login:code:手机号
Content-Type: application/json

{
  "key": "auth:login:code:19283783814",
  "time": 5,
  "timeUnit": "MINUTES",
  "retryCount": 2
}



###

POST {{check_host}}/checkCode/check
Content-Type: application/x-www-form-urlencoded

key = user:register:19283783814 &
code=

