
### 当前是否登录
GET {{user_host}}/user/sso/isLogin
### 登录
GET{{user_host}}/user/sso/login?back=http://localhost:8083/user/sso/isLogin
sa-token:52d6676e-59b9-44a8-a58c-a3396fd865b9

### 返回SSO认证中心登录地址
GET {{user_host}}/user/sso/getSsoAuthUrl?clientLoginUrl=http://localhost:8082/sso/auth
### 根据ticket进行登录
POST {{user_host}}/user/sso/doLoginByTicket
Content-Type: application/x-www-form-urlencoded

ticket=TwK8P7g7KHrTvQIuHNfVIqAXhjbixoxRXEs8LLzMIKwTO3CEPVuGryYtBOUGDAx4