###注册
POST http://localhost:8083/user/register
Content-Type: application/json

{
  "username":"心动",
  "password":"123",
  "email": "",
  "phone":"19283783814",
  "code":"430936"
}
### 当前是否登录
GET http://localhost:8083/user/sso/isLogin
### 返回SSO认证中心登录地址
GET http://localhost:8083/user/sso/getSsoAuthUrl?clientLoginUrl=http://localhost:8083/user/register
### 根据ticket进行登录
POST http://localhost:8083/user/sso/doLoginByTicket
Content-Type: application/x-www-form-urlencoded

ticket=VjNnnemWu6sunbPPwB7we0eZRAauJgZij1xNYx4f3NsKKlmkpc5NLBjRpRwK8ay7